### PR TITLE
Replace playwright with JSDOM

### PR DESCRIPTION
**Pull request by Zacharia2**
image

image

### CODE REVIEW

**Review by Jermolene — COMMENTED** [review]
Thank you @Zacharia2.

I would prefer to make the backend switchable between JSDom and Playwright, with the new default being JSDom.

There are quite a few changes mixed together in this PR:

* Formatting changes (particularly to comments)
* Coding style changes (eg changing `("" + index)` to `index.toString()`)
* Bug fixes (eg changing `document` to `doc` in getPageText())
* Replacing Playwright with JSDom

It would make the commit history clearer if we could split this into two PRs: one for the switch to JSDom, and one for the style changes and cleaning up).

**Comment by Zacharia2** [comment]
Splitting into two PRs is no problem, I just can't switch modules yet. That's hard for me to do.

**Comment by Zacharia2** [comment]
Because I haven't learned yet. hahahaha

**Comment by Zacharia2** [comment]
@Jermolene Split PR Completed

**Comment by Jermolene** [comment]
Thank you @Zacharia2. I notice #20 is closed, will you be resubmitting those changes?

**Comment by Zacharia2** [comment]
OK，@Jermolene

**Comment by Jermolene** [comment]
Hi @Zacharia2 I do apologise again for taking so long over these PRs. I haven't been in a position to work on TWPub for a few weeks, but I am very keen to accept these contributions. I would be very grateful if you could re-establish the PRs.

**Comment by Zacharia2** [comment]
@Jermolene Hi, good evening, I will restore both pr. I appreciate you developing and taking the time to maintain tiddlywiki, I love the note taking software so you don't need to apologize for that.

**Comment by Zacharia2** [comment]
The new recovery PR is now re-opened.

**Pull request closed without merging**
